version: 1.0.{build}
image:
- Visual Studio 2017
configuration: Release
platform: Any CPU
clone_folder: c:\projects\MY_CICD_POC
install:
- ps: >-
    $env:component_version = $env:APPVEYOR_BUILD_VERSION
              If ($env:APPVEYOR_REPO_BRANCH -ne "master") {
                $nuget_suffix = $env:APPVEYOR_REPO_BRANCH.substring(0, [System.Math]::Min(20, $env:APPVEYOR_REPO_BRANCH.length)) -replace "[^a-zA-Z0-9\-]","-"
                $env:component_version = $env:component_version + "-" + $nuget_suffix
              }
              Write-Host "Nuget Component Version:" $env:component_version
build: off
artifacts:
- path: '\MY_CICD_POC\Artifact.zip'
  name: TestDeployment
